### PR TITLE
Fix Spire

### PR DESCRIPTION
**Pull request by NikitaSkrynnik**
## Description
Fixes for bugs in heal, monolith and interdomain examples that were caused by spire update

## Issue link
https://github.com/networkservicemesh/integration-k8s-kind/pull/803

## How Has This Been Tested?

- [ ] Added unit testing to cover
- [x] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [x] Bug fix
- [ ] New functionality
- [ ] Documentation
- [ ] Refactoring
- [ ] CI

### CODE REVIEW

**Review by szvincze — COMMENTED** [review]
Maybe the relative paths should be converted to github.com links with references.

**Review by szvincze — APPROVED** [review]
Looks good to me.

**Review by denis-tingaikin — APPROVED** [review]
@szvincze Many thanks for helping :+1:

**Comment by denis-tingaikin** [comment]
@glazychev-art Do you have any comments on this?

**Pull request merged**
