### PR TITLE
fix: cert generating for spire can fail on CI

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

## Motivation

Fixes https://github.com/networkservicemesh/integration-k8s-kind/pull/270

### CODE REVIEW

**Comment by edwarnicke** [comment]
Could you say more about the problem?  I am loath to require users to install OpenSSL to try an example

**Comment by denis-tingaikin** [comment]
@edwarnicke We need to generate and share cert between two spire servers. To avoid using openssl we could rewrite examples with interdomain to using spire federation after release.

**Comment by edwarnicke** [comment]
Could we open an issue to revisit this?  I'm not super happy with the usability issue...

**Comment by denis-tingaikin** [comment]
@edwarnicke Sure! We'll improve this by using spire federation: https://github.com/networkservicemesh/deployments-k8s/issues/1638

**Pull request merged**
