### PR TITLE
feat: add vl3 dns example

### PR DESCRIPTION
**Pull request by denis-tingaikin**

### CODE REVIEW

**Comment by denis-tingaikin** [comment]
Here has failed refecheck job due to https://github.com/networkservicemesh/deployments-k8s/issues/6645

**Comment by denis-tingaikin** [comment]
Preview: https://github.com/networkservicemesh/deployments-k8s/blob/2e79f744eacb5f81ab2070350523b8753ad82923/examples/features/vl3-dns/README.md

**Comment by edwarnicke** [comment]
Will we be doing a interdomain example as well?

**Comment by edwarnicke** [comment]
Or is this presumed to 'just work' for interdomain and so we should simply think of this as focusing attention on the feature?

**Comment by denis-tingaikin** [comment]
@edwarnicke I think it will be a not big problem to create an interdomain example. Can we do this in the separate PR?

**Comment by edwarnicke** [comment]
> @edwarnicke I think it will be a not big problem to create an interdomain example. Can we do this in the separate PR?

Yes :)

**Pull request merged**
