### PR TITLE
Examples with different SPIRE restarts

### PR DESCRIPTION
**Pull request by szvincze**
Signed-off-by: Szilard Vincze <szilard.vincze@est.tech>

## Description
Four test cases added to healing examples:
1) SPIRE agents restart
2) SPIRE server restart
3) Both SPIRE server and agents restart
4) SPIRE upgrade-like deployment removal and re-installation

## Issue link
-

## How Has This Been Tested?

- [ ] Added unit testing to cover
- [x] Tested manually
- [x] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [ ] Bug fix
- [ ] New functionallity
- [ ] Documentation
- [ ] Refactoring
- [x] CI

### CODE REVIEW

**Comment by denis-tingaikin** [comment]
Woot! We also thought about this kind of testing. So this is looking very useful.


@glazychev-art , @NikitaSkrynnik , @ThetaDR Review is welcome :)

**Comment by denis-tingaikin** [comment]
@szvincze Have yo tested it with other tests in heal suite?

**Comment by szvincze** [comment]
> @szvincze Have you tested it with other tests in heal suite?

@denis-tingaikin Firstly just one by one, then I inserted into heal suite and I ran the complete suite with success.

**Review by denis-tingaikin — APPROVED** [review]
Looks good

**Pull request merged**
